apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webserver
  template:
    metadata:
      labels:
        run: webserver
    spec:
      containers:
      - image: nginx
        name: webserver
        ports:
        - containerPort: 80
